### ISSUE TITLE
两次评论信息不一样时候，评论最外面展示的是最早的一条信息而不是最近的一条

### ISSUE THREAD

**Issue by 94dreamer** [actions-cool/maintain-one-comment#3]
遇到的问题：
两次评论信息不一样时候，评论最外面展示的是最早的一条信息而不是最近的一条
<img width="991" alt="wecom-temp-9a4746e26f90937365438d1938e05a7b" src="https://user-images.githubusercontent.com/15634204/147526972-71fb1e42-a51f-4005-a969-0f9fd244d644.png">

期望的：
应该覆盖掉最早的信息，最近的成功信息应该展示在外面，可以减少点击查看和误会

**Comment by xrkffgg** [comment]
应该不是这样的

**Comment by xrkffgg** [comment]
看下 是不是 触发了 2 次

**Comment by 94dreamer** [comment]
@xrkffgg  的确好像是触发了2次 https://github.com/Tencent/tdesign-react/pull/121

**Comment by xrkffgg** [comment]
workflow 里为啥校验邮件。。。这是不接受外部 PR 么

**Comment by 94dreamer** [comment]
@xrkffgg  这是不允许内部邮箱提交。。。

**Comment by 94dreamer** [comment]
![image](https://user-images.githubusercontent.com/15634204/147772232-7d1eb621-66d3-4d0c-9315-11a2e96a46fa.png)

https://github.com/Tencent/tdesign-vue/pull/139 这个也是最近的PR 预览产物没有覆盖最早的Deploy PR Preview failed.

**Comment by xrkffgg** [comment]
1. 用 Squase 别用 merge
2. 你 merge 的时候应该触发的是公司邮箱
3. 最简单的，去掉公司邮箱限制

**Comment by 94dreamer** [comment]
@xrkffgg  我不是要解决邮箱限制问题 我想要解决的是 maintain-one-comment 多次并且最近的没有覆盖的问题

**Comment by xrkffgg** [comment]
> @xrkffgg 我不是要解决邮箱限制问题 我想要解决的是 maintain-one-comment 多次并且最近的没有覆盖的问题

原因就是 上面的  1 、2

**Comment by 94dreamer** [comment]
@xrkffgg 能够解释下吗 或者说得更具体写吗，谢谢。 
 1 、2我没有get到你的意思

**Comment by xrkffgg** [comment]
你使用 Merge Request 会生成一个新的 commit 信息，我猜测这个 commit 是使用你公司的邮箱，这样就会触发校验 CI 失败。

别人在同步主分支代码时，会继承这个失败。

**Comment by 94dreamer** [comment]
@xrkffgg 邮件校验是检查pr最近一次的commit

**Comment by xrkffgg** [comment]
你可以看下 https://github.com/Tencent/tdesign-react/pull/164

- 成功 https://github.com/Tencent/tdesign-react/actions/runs/1653367715

- 失败 https://github.com/Tencent/tdesign-react/actions/runs/1653385336

**Comment by 94dreamer** [comment]
@xrkffgg  看到了触发了一次成功 一次失败，但是在 https://github.com/Tencent/tdesign-react/runs/4701254703 这个 pr 的action 并没有发现哪里触发了失败

log_emails=$(git log --pretty=format:"%ae" -1)    -1的意思是取最近一次commit

**Comment by 94dreamer** [comment]
![image](https://user-images.githubusercontent.com/15634204/148170729-26750e1a-e9e3-4161-8b37-e8d9d7495464.png)
并且 失败 https://github.com/Tencent/tdesign-react/actions/runs/1653385336
这个的Conclusion也是success

**Comment by xrkffgg** [comment]
奇怪

**Comment by 94dreamer** [comment]
@xrkffgg  咨询一个问题，我关于触发的一个奇怪问题。

我重复执行了 https://github.com/Tencent/tdesign-react/pull/204 这个的 构建 action ，期望去观察他触发的 预览 action。
发现 预览action 里面 接受到的 workflow_id 和 pr 居然是 209。
pull/209 是 合并到 develop 分支的最后一个 pr， 所以我猜测触发 workflow_run 的机制是最后一个 pr【209】，而不是当前完成的 pr 的 action【204】

**Comment by xrkffgg** [comment]
其实触发 workflow 都会的。我们不关注哪个 PR 触发的。只要知道，触发后的拿到结果是一致的。
即
- 上传的预览地址
- 上次的 PR number 

这样在发布的时候，就会在这个 PR 里，更新这个预览地址。

**Comment by 94dreamer** [comment]
@xrkffgg  我找到问题了。

ant 同样应该存在这个问题，dawidd6/action-download-artifact 的用法有问题。

```
uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr
```
workflow_id 首先是触发工作流文件的id，这个是固定的。
因此这这个情况下，则将下载最近成功完成的工作流运行的压缩文件。而不是对应的pr。
这意味着重复触发 204 的actions 时候，会下载 209 的压缩文件。因为 pull/209是最近的

**Comment by 94dreamer** [comment]
我要是修复好了 可以给 ant 提 pr

**Comment by 94dreamer** [comment]
修好了 @xrkffgg  https://github.com/Tencent/tdesign-react/pull/204

**Comment by xrkffgg** [comment]
优秀

**Comment by 94dreamer** [comment]
![image](https://user-images.githubusercontent.com/15634204/148971890-1a28a796-5623-4298-9259-411171bb996b.png)
